version: '3.9'

# This compose file runs both the backend investment tracker and an Ollama
# language model service.  The backend container builds from the provided
# Dockerfile and is configured to call the Ollama service using
# environment variables.  The Ollama service uses the official image
# and listens on the default port 11434.  A persistent volume is
# attached to preserve downloaded models across restarts.

services:
  backend:
    build: ./investments-app
    ports:
      - "3000:3000"
    environment:
      # Configure the backend to talk to the ollama service by name
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    depends_on:
      ollama:
        condition: service_healthy
  ollama-init:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    command: pull llama2
    depends_on:
      ollama:
        condition: service_healthy
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    command: serve
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  ollama-data:
    # A named volume for storing downloaded LLM weights
    driver: local
